[package]
name = "btc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin={git="https://github.com/rust-bitcoin/rust-bitcoin.git", features=["rand-std"]}